# Generated by Django 2.2.1 on 2019-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_auto_20190527_1109'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pulse',
            constraint=models.CheckConstraint(check=models.Q(('max_rabi_rate__gte', 0), ('max_rabi_rate__lte', 100)), name='max_rabi_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='pulse',
            constraint=models.CheckConstraint(check=models.Q(('polar_angle__gte', 0), ('polar_angle__lte', 1)), name='polar_angle_range'),
        ),
    ]
