# Generated by Django 2.2.1 on 2019-05-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0003_auto_20190527_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
